id: P0A1D1FA1
initial_creation_type: input
source_metadata:
  title: Mayum Tsering Wangmo Series
  language: fr
  description: 'Texts by and about Pema Tsering Wangmo (padma tshe ring dbang mo)
    of the Lakar family, the mother of the Seventh Dzogchen Rinpoche and Sogyal Rinpoche:'
  volume:
    9443429cb39b45cca0ef462762ea29b8:
      title: A Brief History of the Lakar Family
      parent: History
    4f05c516c8484ec6984fe76b4de2b805:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
created_at: '2022-03-01T00:44:27.788459'
last_modified_at: '2022-03-01T00:44:27.788461'
